export const BEGIN_STORING_USER = "BEGIN_STORING_USER";
export const STORE_USER = "STORE_USER";
export const STORE_USER_IN_LOCALSTORAGE = "STORE_USER_IN_LOCALSTORAGE"; // Can be removed replaced by just localStorage.add
export const STORE_AUTHENTICATION_TOKEN = "STORE_AUTHENTICATION_TOKEN";
export const STORE_API_TOKEN = "STORE_API_TOKEN";
export const STORE_ACCOUNT_CONFIRMATION_TOKEN =
  "STORE_ACCOUNT_CONFIRMATION_TOKEN";

export const BEGIN_AUTHENTICATING = "BEGIN_AUTHENTICATING";
export const SUCCESS_AUTHENTICATING = "SUCCESS_AUTHENTICATING";
export const FAILURE_AUTHENTICATING = "FAILURE_AUTHENTICATING";

export const BEGIN_CONFIRMING_ACCOUNT = "BEGIN_CONFIRMING_ACCOUNT";
export const SUCCESS_CONFIRMING_ACCOUNT = "SUCCESS_CONFIRMING_ACCOUNT";
export const FAILURE_CONFIRMING_ACCOUNT = "FAILURE_CONFIRMING_ACCOUNT";

export const BEGIN_SIGNING_OUT = "BEGIN_SIGNING_OUT";
export const SIGN_OUT = "SIGN_OUT";
export const SUCCESS_SIGNING_OUT = "SUCCESS_SIGNING_OUT";
export const FAILURE_SIGNING_OUT = "FAILURE_SIGNING_OUT";

export const BEGIN_SIGNING_IN = "BEGIN_SIGNING_IN";
export const SIGN_IN = "SIGN_IN";
export const SUCCESS_SIGNING_IN = "SUCCESS_SIGNING_IN";
export const FAILURE_SIGNING_IN = "FAILURE_SIGNING_IN";

export const BEGIN_SIGNING_UP = "BEGIN_SIGNING_UP";
export const SIGN_UP = "SIGN_UP";
export const SUCCESS_SIGNING_UP = "SUCCESS_SIGNING_UP";
export const FAILURE_SIGNING_UP = "FAILURE_SIGNING_UP";
export const RESET_IS_SIGNED_UP = "RESET_IS_SIGNED_UP";

export const SET_CONFIRM_COOKIE_FLAG = "SET_CONFIRM_COOKIE_FLAG";
export const BEGIN_CONFIRM_24_HOUR_MEAL_RESET =
  "BEGIN_CONFIRM_24_HOUR_MEAL_RESET";
export const SUCCESS_CONFIRMING_24_HOUR_MEAL_RESET =
  "SUCCESS_CONFIRMING_24_HOUR_MEAL_RESET";
export const FAILURE_CONFIRMING_24_HOUR_MEAL_RESET =
  "FAILURE_CONFIRMING_24_HOUR_MEAL_RESET";

export const MEASUREMENT_REQUIRED = "MEASUREMENT_REQUIRED";
export const FOOD_OR_DRINK_REQUIRED = "FOOD_OR_DRINK_REQUIRED";
export const FOODDRINK_NAME_REQUIRED = "FOODDRINK_NAME_REQUIRED";

export const BEGIN_SAVING_NEW_MEASUREMENT = "BEGIN_SAVING_NEW_MEASUREMENT";
export const SUCCESS_SAVING_NEW_MEASUREMENT = "SUCCESS_SAVING_NEW_MEASUREMENT";
export const FAILURE_SAVING_NEW_MEASUREMENT = "FAILURE_SAVING_NEW_MEASUREMENT";

export const BEGIN_ADDING_NEW_MEASUREMENT = "BEGIN_ADDING_NEW_MEASUREMENT";
export const ADD_NEW_MEASUREMENT = "ADD_NEW_MEASUREMENT";
export const SUCCESS_ADDING_NEW_MEASUREMENT = "SUCCESS_ADDING_NEW_MEASUREMENT";
export const FAILURE_ADDING_NEW_MEASUREMENT = "FAILURE_ADDING_NEW_MEASUREMENT";

export const BEGIN_DELETING_MEASUREMENT = "BEGIN_DELETING_MEASUREMENT";
export const SUCCESS_DELETING_MEASUREMENT = "SUCCESS_DELETING_MEASUREMENT";
export const FAILURE_DELETING_MEASUREMENT = "FAILURE_DELETING_MEASUREMENT";

export const BEGIN_CREATING_NEW_MEAL = "BEGIN_CREATING_NEW_MEAL";
export const SUCCESS_CREATING_NEW_MEAL = "SUCCESS_CREATING_NEW_MEAL";
export const FAILURE_CREATING_NEW_MEAL = "FAILURE_CREATING_NEW_MEAL";

export const DASHBOARD_UPDATE_ERROR = "DASHBOARD_UPDATE_ERROR"; // TODO possibly delete.
export const SAVE_MEASUREMENT_ERROR = "SAVE_MEASUREMENT_ERROR";

export const BEGIN_SAVING_NEW_FOOD_DRINK = "BEGIN_SAVING_NEW_FOOD_DRINK";
export const SUCCESS_SAVING_NEW_FOOD_DRINK = "SUCCESS_SAVING_NEW_FOOD_DRINK";
export const FAILURE_SAVING_NEW_FOOD_DRINK = "FAILURE_SAVING_NEW_FOOD_DRINK";
export const PUSH_TO_SAVE_FOOD_DRINK_ERRORS = "PUSH_TO_SAVE_FOOD_DRINK_ERRORS";

export const BEGIN_SAVING_MEALS = "BEGIN_SAVING_MEALS";
export const SUCCESS_SAVING_MEALS = "SUCCESS_SAVING_MEALS";
export const FAILURE_SAVING_MEALS = "FAILURE_SAVING_MEALS";

export const TOGGLE_MENU = "TOGGLE_MENU";

export const SET_LOADER = "SET_LOADER";

export const SET_ALERT = "SET_ALERT";

export const BEGIN_CALCULATING_TOTALS = "BEGIN_CALCULATING_TOTALS";
export const CALCULATE_TOTALS = "CALCULATE_TOTALS";
export const CALCULATE_TOTALS_SUCCESS = "CALCULATE_TOTALS_SUCCESS";
export const CALCULATE_TOTALS_FAILURE = "CALCULATE_TOTALS_FAILURE";
export const BEGIN_MEAL_ADDITION_CALCULATION =
  "BEGIN_MEAL_ADDITION_CALCULATION";
export const MEAL_ADDITION_CALCULATION = "MEAL_ADDITION_CALCULATION";
export const MEAL_ADDITION_CALCULATION_SUCCESS =
  "MEAL_ADDITION_CALCULATION_SUCCESS";
export const MEAL_ADDITION_CALCULATION_FAILURE =
  "MEAL_ADDITION_CALCULATION_FAILURE";

export const SET_STAY_BOX = "SET_STAY_BOX";

export const TOGGLE_DETAILS = "TOGGLE_DETAILS";

export const BEGIN_PASSWORD_RESET = "BEGIN_PASSWORD_RESET";
export const SUCCESS_PASSWORD_RESET = "SUCCESS_PASSWORD_RESET";
export const FAILURE_PASSWORD_RESET = "FAILURE_PASSWORD_RESET";

export const SET_FORM_ERROR = "SET_FORM_ERROR";
